######################################################################
# Automatically generated by qmake (3.0) Sze okt. 7 15:21:30 2015
######################################################################

TEMPLATE = app
TARGET = debug
INCLUDEPATH += .

# Input
SOURCES += qrc_GUI.cpp
